name: stylebot

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate
        run: python3 ./bin/build-stylebot-file.py > stylebot.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: stylebot.json
          path: stylebot.json
